helpdesk/helpdesk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('tickets/', include('tickets.urls')),
]

helpdesk/tickets/urls.py
from django.urls import path
from tickets import views

urlpatterns = [
    path('', views.TicketsList.as_view(), name="tickets list"),
    path('add/', views.NewTicket.as_view(), name="add ticket"),
    path('<int:ticket_id>/', views.TicketDetails.as_view(), name="ticket details"),
]

helpdesk/users/urls.py
from django.contrib import admin
from django.urls import include, path
from users import views

urlpatterns = [
    path('', views.index, name='profile'),
    path('accounts/login/', views.SigninView.as_view(), name='login'),
    path('accounts/edit/', views.UserProfile.as_view(), name='edit profile'),
    path('accounts/profile/', views.redirectToProfile),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.RegisterView.as_view(), name='register'),
]

helpdesk/tickets/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

class Ticket(models.Model):
    title = models.CharField(max_length=254, default="") #check for default value
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    dateTime = models.DateTimeField(default=timezone.now)
    lastUpdate = models.DateTimeField(auto_now=True)

    States = (
        ('Waiting for response', 'Waiting for response'),
        ('Answered', 'Answered'),
        ('Closed', 'Closed'),
    )
    state = models.CharField(max_length=20, choices=States, default="Waiting for response")

    Priorities = (
        ('Low', 'Low'),
        ('Medium', 'Medium'),
        ('High', 'High'),
    )
    priority = models.CharField(max_length=6, choices=Priorities, default=0)

    def __str__(self):
        return self.title

class Comment(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    from_owner = models.BooleanField(default=True)
    comment = models.TextField(blank=False, default="")
    dateTime = models.DateTimeField(auto_now=True)

helpdesk/tickets/forms.py
from django.forms import ModelForm
from tickets.models import Ticket, Comment
from django.contrib.auth import get_user_model
from django.conf import settings
from django.utils import timezone
from django.core.exceptions import ValidationError

def is_member(user, *group_names):
    if user.is_authenticated:
        if bool(user.groups.filter(name__in=group_names)) or user.is_superuser:
            return True
    return False  

class TicketForm(ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        return super().__init__(*args, **kwargs)

    def save(self, request):
        ticket = super().save(commit=False)
        if ticket.creator is None:
            ticket.creator = request.user
        ticket.save()
        return ticket
    
    def clean(self):
        cd = self.cleaned_data

        if cd.get('creator') is not None:
            if get_user_model().objects.get(id=cd.get('creator').id).groups.filter(name='clients').exists():
                pass
            else:
                raise ValidationError("Unknown Client Selected!")
        else:
            if is_member(self.request.user, 'supports'):
                raise ValidationError("Unknown Client Selected!")
            else:
                cd['creator'] = self.request.user
        
        return cd
    
    class Meta:
        model = Ticket
        fields = ['title', 'priority', 'creator']

class CommentForm(ModelForm):
    def save(self, request, ticket):
        comment = super().save(commit=False)
        if request.user == ticket.creator:
            ticket.state = "Waiting for response"
            comment.from_owner = True
        else:
            ticket.state = "Answered"
            comment.from_owner = False
        ticket.save()
        comment.ticket = ticket
        comment.save()
        ticket.lastUpdate = timezone.now()
        return comment

    class Meta:
        model = Comment
        fields = ['comment']

helpdesk/tickets/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, CreateView
from tickets.forms import TicketForm, CommentForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from tickets.models import Ticket, Comment
from django.contrib.auth import get_user_model
from django.conf import settings
from django.http import Http404

def is_member(user, *group_names):
    if user.is_authenticated:
        if bool(user.groups.filter(name__in=group_names)) or user.is_superuser:
            return True
    return False   

class NewTicket(TemplateView):
    template_name = "tickets/add-ticket.html"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ticketForm'] = TicketForm()
        context['commentForm'] = CommentForm()
        context['is_support'] = is_member(self.request.user, 'supports')
        if (context['is_support']):
            context['clients'] = []
            context['clients'] = get_user_model().objects.filter(groups__name='clients')
        context['user_name'] = str(self.request.user)
        return context
    
    def post(self, request):
        ticketForm = TicketForm(request.POST, request=request)
        commentForm = CommentForm(request.POST)

        if ticketForm.is_valid() and commentForm.is_valid():
            ticket = ticketForm.save(request)
            comment = commentForm.save(request, ticket)
            return redirect('ticket details', ticket_id=ticket.id)
        context = self.get_context_data()
        context['ticketForm'] = ticketForm
        context['commentForm'] = commentForm
        return render(request, 'tickets/add-ticket.html', context)

class TicketsList(ListView):
    model = Ticket
    template_name = "tickets/tickets-list.html"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        if self.request.user.has_perm('users.support'):
            return Ticket.objects.all()
        elif self.request.user.has_perm('users.client'):
            return Ticket.objects.filter(creator=self.request.user)
        return []
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_support'] = self.request.user.has_perm('users.support')
        context['user_name'] = str(self.request.user)
        return context

class TicketDetails(ListView):
    template_name = "tickets/ticket.html"
    context_object_name = "comments"
    model = Comment
    paginate_by = 10

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_superuser or Ticket.objects.filter(creator=request.user, id=kwargs['ticket_id']):
            return super().dispatch(request, *args, **kwargs)
        raise Http404
    
    def get_queryset(self):
        return Comment.objects.filter(ticket=self.kwargs['ticket_id']).order_by('-dateTime')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['commentForm'] = CommentForm()
        context['ticket'] = Ticket.objects.get(id=self.kwargs['ticket_id'])
        context['is_support'] = self.request.user.has_perm('users.support')
        context['user_name'] = str(self.request.user)
        return context
    
    def post(self, request, *args, **kwargs):
        commentForm = CommentForm(request.POST)
        if commentForm.is_valid():
            commentForm.save(request, Ticket.objects.get(id=kwargs['ticket_id']))
            return self.get(request, kwargs)
        self.get(request, *args, **kwargs)
        context = self.get_context_data(**kwargs) #check for error on empty message
        context['commentForm'] = commentForm
        return render(request, self.template_name, context)
    
    def get(self, request, *args, **kwargs):
        close_state = request.GET.get('close', None)
        if close_state is not None and close_state == "true":
            ticket = Ticket.objects.get(id=kwargs['ticket_id'])
            ticket.state = "Closed"
            ticket.save()
            return redirect("tickets list")
        return super().get(request, *args, **kwargs)

helpdesk/templates/tickets/add-ticket.html
<!doctype html>
{% load static %}
<html class="no-js" lang="en">

<head>
    {% include "./base/head.html" with title="Add Ticket" %}
</head>

<body class="body-bg">
    <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <!-- preloader area start -->
    <div id="preloader">
        <div class="loader"></div>
    </div>
    <!-- preloader area end -->
    <!-- page container area start -->
    <div class="horizontal-main-wrapper">
        {% include './base/header.html' with name=user_name %}
        <!-- main content area start -->
        <div class="main-content">
            <div class="main-content-inner">
                <div class="container">
                    <div class="row">
                        <!-- basic form start -->
                        <div class="col-12 mt-5">
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="header-title">Ticket Information</h4>
                                    {% if ticketForm.errors or commentForm.errors %}
                                    <div class="alert alert-danger" role="alert">
                                        
                                        {% for field in ticketForm %}
                                            {% for error in field.errors %}
                                                <strong>{{ field.label }}:</strong> {{ error|escape }}<br>
                                            {% endfor %}
                                        {% endfor %}
                                        {% for error in ticketForm.non_field_errors %}
                                            {{ error|escape }}<br>
                                        {% endfor %}

                                        {% for field in commentForm %}
                                            {% for error in field.errors %}
                                                <strong>{{ field.label }}:</strong> {{ error|escape }}<br>
                                            {% endfor %}
                                        {% endfor %}
                                        {% for error in commentForm.non_field_errors %}
                                            {{ error|escape }}<br>
                                        {% endfor %}
                                    </div>
                                    {% endif %}
                                    <form method="POST">
                                        {% csrf_token %}
                                        <div class="form-row align-items-center">
                                            {% if is_support %}
                                            <div class="col-sm-6 my-1">
                                            {% else %}
                                            <div class="col-sm-9 my-1">
                                            {% endif %}
                                                <label class="col-form-label" for="id_title">Title</label>
                                                <input type="text" class="form-control" name="title" required maxlength="254" id="id_title" placeholder="Enter Title" value="{{ ticketForm.title.value }}">
                                            </div>
                                            {% if is_support %}
                                            <div class="col-sm-3 my-1">
                                                <label class="col-form-label" for="id_creator">To</label>
                                                <select name="creator" required id="id_creator" class="form-control">
                                                    <option value selected>---------</option>
                                                    {% for x in clients %}
                                                    <option value="{{ x.id }}">{{ x }}</option>
                                                    {% endfor %}
                                                </select>
                                            </div>
                                            {% endif %}
                                            <div class="col-sm-3 my-1">
                                                <label class="col-form-label" for="id_priority">Priority</label>
                                                <select name="priority" id="id_priority" class="form-control">
                                                    <option value="Low" selected>Low</option>
                                                    <option value="Medium">Medium</option>
                                                    <option value="High">High</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="id_comment">Message</label>
                                            <textarea rows="10" required class="form-control" id="id_comment" name="comment" placeholder="Enter your message...">{{ commentForm.comment.value }}</textarea>
                                        </div>
                                        <button type="submit" class="btn btn-primary mt-4 pr-4 pl-4">Submit</button>
                                        <a role="button" class="btn btn-secondary mt-4 pr-4 pl-4" href="{% url 'tickets list' %}">Cancel</a>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <!-- basic form end -->
                    </div>
                </div>
            </div>
        </div>
        <!-- main content area end -->
        <!-- footer area start-->
        <footer>
            <div class="footer-area">
                <p>© Copyright 2019. All right reserved. <a href="https://github.com/clwluvw/">Seena Fallah</a>.</p>
            </div>
        </footer>
        <!-- footer area end-->
    </div>
    <!-- page container area end -->
    {% include "./base/footer.html" %}

</html>

helpdesk/templates/tickets/ticket.html
<!doctype html>
{% load static %}
<html class="no-js" lang="en">

<head>
        {% include "./base/head.html" with title="Ticket Details" %}
</head>

<body class="body-bg">
    <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <!-- preloader area start -->
    <div id="preloader">
        <div class="loader"></div>
    </div>
    <!-- preloader area end -->
    <!-- page container area start -->
    <div class="horizontal-main-wrapper">
        {% include './base/header.html' with name=user_name %}
        <!-- main content area start -->
        <div class="main-content">
            <div class="main-content-inner">
                <div class="container">
                    <div class="row">
                        <!-- Bootstrap Grid start -->
                        <div class="col-12 mt-5">
                            <div class="card">
                                <div class="card-body">
                                    <div class="header-title">{{ ticket.title }}</div>
                                    <!-- Start 4 column grid system -->
                                    <div class="row">
                                        <div class="col-md-4">
                                            <button type="button" id="theButton" class="btn btn-success btn-lg btn-block" onclick="jQuery('#comment-section').slideToggle()">Add Comment</button>
                                        </div>
                                        <div class="col-md-4">
                                            <button type="button" class="btn btn-danger btn-lg btn-block" onclick="window.location='?close=true'">Close Ticket</a>
                                        </div>
                                        <div class="col-md-4">
                                            <a class="btn btn-secondary btn-lg btn-block" role="button" href="{% url 'tickets list' %}">Back to Tickets</a>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col">
                                            <div class="card" id="comment-section" style="display:none;">
                                                <div class="card-body">
                                                    {% if commentForm.errors %}
                                                    <div class="alert alert-danger" role="alert">
                                                        {% for field in commentForm %}
                                                            {% for error in field.errors %}
                                                                <strong>{{ field.label }}:</strong> {{ error|escape }}<br>
                                                            {% endfor %}
                                                        {% endfor %}
                                                        {% for error in commentForm.non_field_errors %}
                                                            {{ error|escape }}<br>
                                                        {% endfor %}
                                                    </div>
                                                    {% endif %}
                                                    <h4 class="header-title">Add Comment</h4>
                                                    <form method="POST">
                                                        {% csrf_token %}
                                                        <div class="form-group">
                                                            <textarea rows="10" required class="form-control" id="id_comment" name="comment" placeholder="Enter your message..."></textarea>
                                                        </div>
                                                        <button type="submit" class="btn btn-primary mt-4 pr-4 pl-4">Submit</button>
                                                    </form>
                                                </div>
                                            </div>
                                            {% if commentForm.errors %}
                                            <script>document.getElementById('comment-section').style.display = null;</script>
                                            {% endif %}

                                            <div class="card">
                                                <div class="card-body">
                                                    <h4 class="header-title">Comments</h4>
                                                    {% for x in comments %}
                                                    <ul class="ticket-comment list-group">
                                                        {% if x.from_owner == True %}
                                                            <li class="list-group-item active">{{ x.ticket.creator }} <span class="comment-date">{{ x.dateTime }}</span></li>
                                                        {% else %}
                                                            <li class="list-group-item disabled">Help Desk <span class="comment-date">{{ x.dateTime }}</span></li>
                                                        {% endif %}
                                                        <li class="list-group-item">{{ x.comment }}</li>
                                                    </ul>
                                                    {% endfor %}
                                                </div>
                                            </div>

                                            {% if is_paginated %}
                                            <div class="card">
                                                <div class="card-body">
                                                    <nav aria-label="...">
                                                        <ul class="pagination pg-color-border">
                                                            {% if page_obj.has_previous %}
                                                            <li class="page-item">
                                                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                                                            </li>
                                                            {% else %}
                                                            <li class="page-item disabled">
                                                                <a class="page-link" href="#" tabindex="-1">Previous</a>
                                                            </li>
                                                            {% endif %}
                                                            {% for i in i|rjust:page_obj.paginator.num_pages %}
                                                                {% if forloop.last %}

                                                                {% elif forloop.counter == page_obj.number %}
                                                                <li class="page-item active">
                                                                    <a class="page-link">{{ page_obj.number }} <span class="sr-only">(current)</span></a>
                                                                </li>
                                                                {% elif forloop.counter != 0 %}
                                                                <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
                                                                {% endif %}
                                                            {% endfor %}
                                                            {% if page_obj.has_next %}
                                                            <li class="page-item">
                                                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                                                            </li>
                                                            {% else %}
                                                            <li class="page-item disabled">
                                                                <a class="page-link" href="#">Next</a>
                                                            </li>
                                                            {% endif %}
                                                        </ul>
                                                    </nav>
                                                </div>
                                            </div>
                                            {% endif %}
                                        </div>
                                        
                                        <div class="col col-lg-4">
                                            <div class="card">
                                                <div class="card-body">
                                                    <h4 class="header-title">Info</h4>
                                                    <ul class="list-group">
                                                        {% if is_support %}
                                                        <li class="list-group-item"><i class="fa fa-user"></i><strong>Owner: </strong>{{ ticket.creator }}</li>
                                                        {% endif %}
                                                        <li class="list-group-item"><i class="fa fa-ticket"></i><strong>State: </strong>
                                                            {% if ticket.state == "Waiting for response" %}
                                                            <span class="badge badge-warning">{{ ticket.state }}</span>
                                                            {% elif ticket.state == "Answered" %}
                                                            <span class="badge badge-success">{{ ticket.state }}</span>
                                                            {% else %}
                                                            <span class="badge badge-secondary">{{ ticket.state }}</span>
                                                            {% endif %}
                                                        </li>
                                                        <li class="list-group-item"><i class="fa fa-calendar"></i><strong>Date Created: </strong>{{ ticket.dateTime }}</li>
                                                        <li class="list-group-item"><i class="fa fa-bolt"></i><strong>Priority: </strong>{{ ticket.priority }}</li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Bootstrap Grid end -->
                    </div>
                </div>
            </div>
        </div>
        <!-- main content area end -->
        <!-- footer area start-->
        <footer>
            <div class="footer-area">
                <p>© Copyright 2019. All right reserved. <a href="https://github.com/clwluvw/">Seena Fallah</a>.</p>
            </div>
        </footer>
        <!-- footer area end-->
    </div>
    <!-- page container area end -->
    {% include "./base/footer.html" %}
</body>

</html>